### ISSUE TITLE
Use gulp-sass instead of gulp-ruby-sass

### ISSUE THREAD

**Issue by jonathanobino** [niallobrien/generator-gulp-angularfire#5]
Since I hate ruby I'm not going to install ruby-sass, would you provide al alternative and let us use gulp-sass?

Thanks

**Comment by niallobrien** [comment]
It's been a while since I looked at this project, but I'm sure it uses gulp-sass (libsass).
https://github.com/niallobrien/generator-gulp-angularfire/blob/master/app/templates/_package.json

**Comment by jonathanobino** [comment]
well, I've downloaded this just 5 minutes ago was downloaded with the old ruby-sass, tomorrow I'm going to re-download.. such an unusual thing ( I know it has changed 7 month ago, can't  figure out why I've downloaded the older version). Thanks anyway for your fast reply :D

**Comment by jonathanobino** [comment]
tried right now, it installs ruby-sass again :|

**Comment by niallobrien** [comment]
The package.json references gulp-sass not gulp-ruby-sass. Can you show me
anything specific?

**Comment by jonathanobino** [comment]
http://pastebin.com/RcSvU72K this is the package.json
http://pastebin.com/YJzqvnm0 this is bower.json
http://pastebin.com/BhXgMpkD this is bulp/build.js

**Comment by niallobrien** [comment]
https://github.com/niallobrien/generator-gulp-angularfire/commit/36fb040c73d885f3ffd7ee1cc7e8b39ae6b0dcba

**Comment by jonathanobino** [comment]
yep, installed the generator today :)

**Comment by niallobrien** [comment]
Ah, apologies. I see that npm has v0.0.2 - latest is v 0.0.3. I simply forgot to publish the update to NPM.
I will get this done in the next 24 hours or so.

**Comment by jonathanobino** [comment]
Awesome! Luckily I was going to test things out before the next hackathon :D

**Comment by niallobrien** [comment]
Updated. https://www.npmjs.com/package/generator-gulp-angularfire
Please note that I really don't use this generator so please treat is as a boilerplate of sorts. Feel free to modify and submit any pull-requests you feel others would benefit from.
